name: workflow-filter

on:
  push:
    branches:
      - 'master'
    
  pull_request:
    branches: 
        - feat/branch*/**
    paths-ignore:
      - test.txt
jobs:
  gitworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo workflow info
        run: echo "Workflow event is ${{ github.event_name }}"
